services:
  elasticsearch:
    image: elasticsearch:7.13.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - soogleEs:/usr/share/elasticsearch/data
  scalajs:
    build:
      context: ./docker/frontend
      dockerfile: Dockerfile
    container_name: scalajs
    volumes:
      - .:/app
      - sbtDeps:/root/.sbt
      - sbtCache:/root/.cache

volumes:
  soogleEs:
  sbtDeps:
  sbtCache:
